repositories:
  - name: bndigital
    url: https://dcr.bndigital.dev/chartrepo/library

helmDefaults:
  kubeContext: do-fra1-bndigital
  createNamespace: true
  cleanupOnFail: true

releases:
  - name: ant-chart-demo-website
    namespace: staging
    chart: bndigital/nodejs
    values:
      - image: dcr.bndigital.dev/ant-chart-demo/website:latest
        imagePullSecrets: [ container-registry ]
        ingress:
          enabled: true
          tls: true
          host: ant-chart-demo.bndigital.dev
