apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: nymcard
build:
  artifacts:
  - image: cms
    context: .
    docker:
      dockerfile: packages/cms/Dockerfile
  - image: website
    context: .
    docker:
      dockerfile: packages/website/Dockerfile
  tagPolicy:
    sha256: {}
  local:
    push: false
    useBuildkit: true
deploy:
  helm:
    releases:
    - name: web
      chartPath: charts/web
      overrides:
        image:
          repository: website
    flags:
      upgrade:
      - --install
profiles:
- name: ci
  activation:
  - env: CI=true
  build:
    local:
      push: true
      useBuildkit: true
