{{- if .Values.backend.enabled }} {{- range .Values.backend.persistence.volumes }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" $.Release.Name .name }}
  labels: {{ include "nodejs.labels" $ | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size | quote }}
{{- end }} {{ end }}
