name: Build
on:
  release:
    types:
      - unpublished
  push:
    paths:
      - .github/workflows/codestyle.yml
      - packages/*/src/**/*
jobs:
  build:
    name: Build packages
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install Yarn
        run: npm i -g yarn
      - name: Install dependencies
        run: yarn
      - name: Run linters
        run: yarn lint
      - name: Run tests
        run: yarn build
