name: Upgrade dependencies
on:
  push:
    paths:
      - .github/workflows/upgrade.yml
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
jobs:
  upgrade:
    name: Upgrade dependencies
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install Yarn
        run: npm i -g yarn
      - name: Upgrade package versions
        run: yarn up '*'
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update NPM dependencies
          branch: dependency-update
          title: Update NPM dependencies
          body: Updated package.json with latest versions
          labels: auto-merge,dependency
          reviewers: vladyslavvolkov
